sudo: false
language: python
python:
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "pypy3.5"

install:
  - pip install coverage

script:
  - coverage run --source tryingsnake $(which nosetests) --with-doctest --doctest-extension rst
  - if [[ $TRAVIS_PYTHON_VERSION != pypy* ]]; then coverage report --show-missing ; fi

after_success:
  - if [[ $TRAVIS_PYTHON_VERSION != pypy* ]]; then pip install coveralls --use-mirrors ; coveralls ; fi

