sudo: false
language: python

matrix:
  include:
    - python: "3.6"
      env: PYPY=false
    - python: "3.7"
      env: PYPY=false
    - python: "3.8"
      env: PYPY=false
    # - python: "nightly"
    #   env: PYPY=false
    - python: "pypy3"
      env: PYPY=true

before_script:
  - pip install coveralls pytest pytest-cov
  - if [[ $PYPY = false ]]; then pip install black mypy; fi;
install:
  - pip install .
script:
  - pytest --doctest-modules --cov-report=term-missing --cov=tryingsnake  tryingsnake
  - if [[ $PYPY = false ]]; then mypy tryingsnake; fi;
  - if [[ $PYPY = false ]]; then black --check tryingsnake setup.py; fi;
after_success:
  - coveralls
deploy:
  provider: pypi
  user: __token__
  skip_existing: true
  on:
    tags: true
    branch: master
  password:
    secure: wAnzq8Hf+35Yb/MhpNCy7PHT4CAqZQCIxfymb+V6OdMFaHYtG/cFWw2Kj51AlF6CKgDobfsrtiEpUok/V17qCeoOjSAHeVnbmqxKyu7pNsg3DhkSs5NHHKctwMsPdbsb9/9A1GOhvHPWXyCVL0fX+ZPb7u1ULYGYtz85QMEpm09alLdQlxqe/mb1gOHDRqLscWGnFtmm7j6d/PCjPQcLonfXZ3Kw6s16f2mCEx2saKBDSMzEUYAfVrow+70Ro8p0YhsfERTGB7JsqT1in7/RJLQCt7InT9Vr+BuHOCFBsL3e43OkQ7i0kvb4Amw5w0C3sNQMX0qauGFqRQ5b1j9gkGnJRhZJWdWGKBSH9wUDhNSPIiPgcGGlb2g2CxgH/Lq+Pa7CvxW2oLE9m5GpgXrTGJdzx1xzRpT7Af6t9DsYg/iLPRLF18UV/A9BO5S2zhUJxKGZnzPZpH1UzxsVJI2MCY6akCpFikEmo91N5O7+YSD1Tka5y8fd+DmMRLAdjA1CVyW8mjhVt0ieSWbrMRLi8wjvps6LFWjS8QWLXAX2lXnmrH3qGe/8/3W/nxezxCBUNqKsZsZfrBkPrkpOx2vWwkSe3i25/cxYSNw8cf64Twdk08+r0kBdJJ4wAymWcYOU7qubopilTfF0jpwAsUANIermBOFh2c8C256Qa9n6ByQ=
