sudo: false
language: python
python:
  - "3.6"
  - "3.7"
  - "3.8-dev"  # 3.8 development branch
  - "nightly"  # nightly build
  - "pypy3"

install:
  - pip install coverage
  - pip install .

script:
  - coverage run --source tryingsnake $(which nosetests) --with-doctest --doctest-extension rst
  - if [[ $TRAVIS_PYTHON_VERSION != pypy* ]]; then coverage report --show-missing ; fi

after_success:
  - if [[ $TRAVIS_PYTHON_VERSION != pypy* ]]; then pip install coveralls --use-mirrors ; coveralls ; fi
